#!/usr/bin/env bash

# $ npm start
# ===========
#
# #### [NODE_PATH=.](https://gist.github.com/branneman/8048520)
#
# Eliminate the clutter associated with importing from a deeply nested directory structure.

NODE_PATH=. node ./server/babel-hook.js
